#! /usr/bin/env racket
#lang racket/base

(require json)
(require rackunit)


;; Path (cons Path Path) -> Void
(define (run-test-case executable test-case)
  (define test-case-input-port (open-input-file (car test-case)))
  (define expected-output (read-json (open-input-file (cdr test-case))))
  (define-values (proc child-out child-in e) (subprocess #f test-case-input-port #f #f executable))
  (define actual-output (read-json child-out))
  (define passed? (if (equal? actual-output expected-output) "PASS" "FAIL"))
  (display (string-append (car test-case) " ..... " passed? "\n")))


;; Test milestone 2
(display "--- Board ---\n")
(define milestone-2-test-cases (list (cons "IntegrationTests/3/Tests/0-in.json" "IntegrationTests/3/Tests/0-out.json")
                                     (cons "IntegrationTests/3/Tests/1-in.json" "IntegrationTests/3/Tests/1-out.json")
                                     (cons "IntegrationTests/3/Tests/2-in.json" "IntegrationTests/3/Tests/2-out.json")
                                     (cons "IntegrationTests/3/ForStudents/0-in.json" "IntegrationTests/3/ForStudents/0-out.json")
                                     (cons "IntegrationTests/3/ForStudents/1-in.json" "IntegrationTests/3/ForStudents/1-out.json")
                                     (cons "IntegrationTests/3/ForStudents/2-in.json" "IntegrationTests/3/ForStudents/2-out.json")))
(for ([testcase milestone-2-test-cases])
  (run-test-case "IntegrationTests/3/xboard" testcase))

(display "--- Gamestate ---\n")
;; Test milestone 3
(define milestone-3-test-cases (list (cons "IntegrationTests/4/Tests/0-in.json" "IntegrationTests/4/Tests/0-out.json")
                                     (cons "IntegrationTests/4/Tests/1-in.json" "IntegrationTests/4/Tests/1-out.json")
                                     (cons "IntegrationTests/4/Tests/2-in.json" "IntegrationTests/4/Tests/2-out.json")
                                     (cons "IntegrationTests/4/Tests/3-in.json" "IntegrationTests/4/Tests/3-out.json")
                                     (cons "IntegrationTests/4/Tests/4-in.json" "IntegrationTests/4/Tests/4-out.json")
                                     (cons "IntegrationTests/4/ForStudents/0-in.json" "IntegrationTests/4/ForStudents/0-out.json")
                                     (cons "IntegrationTests/4/ForStudents/1-in.json" "IntegrationTests/4/ForStudents/1-out.json")
                                     (cons "IntegrationTests/4/ForStudents/2-in.json" "IntegrationTests/4/ForStudents/2-out.json")))
(for ([testcase milestone-3-test-cases])
  (run-test-case "IntegrationTests/4/xstate" testcase))

(display "--- Strategy ---\n")
;; Test milestone 4
(define milestone-4-test-cases (list (cons "IntegrationTests/5/Tests/0-in.json" "IntegrationTests/5/Tests/0-out.json")
                                     (cons "IntegrationTests/5/Tests/1-in.json" "IntegrationTests/5/Tests/1-out.json")
                                     (cons "IntegrationTests/5/Tests/2-in.json" "IntegrationTests/5/Tests/2-out.json")
                                     (cons "IntegrationTests/5/Tests/3-in.json" "IntegrationTests/5/Tests/3-out.json")
                                     (cons "IntegrationTests/5/Tests/4-in.json" "IntegrationTests/5/Tests/4-out.json")
                                     (cons "IntegrationTests/5/ForStudents/0-in.json" "IntegrationTests/5/ForStudents/0-out.json")
                                     (cons "IntegrationTests/5/ForStudents/1-in.json" "IntegrationTests/5/ForStudents/1-out.json")
                                     (cons "IntegrationTests/5/ForStudents/2-in.json" "IntegrationTests/5/ForStudents/2-out.json")))
(for ([testcase milestone-4-test-cases])
  (run-test-case "IntegrationTests/5/xchoice" testcase))

(display "--- Games ---\n")
;; Test milestone 5
(define milestone-5-test-cases (list (cons "IntegrationTests/6/Tests/0-in.json" "IntegrationTests/6/Tests/0-out.json")
                                     (cons "IntegrationTests/6/Tests/1-in.json" "IntegrationTests/6/Tests/1-out.json")
                                     (cons "IntegrationTests/6/Tests/2-in.json" "IntegrationTests/6/Tests/2-out.json")
                                     (cons "IntegrationTests/6/ForStudents/0-in.json" "IntegrationTests/6/ForStudents/0-out.json")
                                     (cons "IntegrationTests/6/ForStudents/1-in.json" "IntegrationTests/6/ForStudents/1-out.json")
                                     (cons "IntegrationTests/6/ForStudents/2-in.json" "IntegrationTests/6/ForStudents/2-out.json")))
(for ([testcase milestone-5-test-cases])
  (run-test-case "IntegrationTests/6/xgames" testcase))

(display "--- Fault tolerance 1 ---\n")
;; Test milestone 6
(define milestone-6-test-cases (list (cons "IntegrationTests/7/Tests/0-in.json" "IntegrationTests/7/Tests/0-out.json")
                                     (cons "IntegrationTests/7/Tests/1-in.json" "IntegrationTests/7/Tests/1-out.json")
                                     (cons "IntegrationTests/7/Tests/2-in.json" "IntegrationTests/7/Tests/2-out.json")
                                     (cons "IntegrationTests/7/ForStudents/0-in.json" "IntegrationTests/7/ForStudents/0-out.json")
                                     (cons "IntegrationTests/7/ForStudents/1-in.json" "IntegrationTests/7/ForStudents/1-out.json")
                                     (cons "IntegrationTests/7/ForStudents/2-in.json" "IntegrationTests/7/ForStudents/2-out.json")))
(for ([testcase milestone-6-test-cases])
  (run-test-case "IntegrationTests/7/xbad" testcase))

(display "--- Fault tolerance 2 ---\n")
;; Test milestone 7
(define milestone-7-test-cases (list (cons "IntegrationTests/8/Tests/0-in.json" "IntegrationTests/8/Tests/0-out.json")
                                     (cons "IntegrationTests/8/Tests/1-in.json" "IntegrationTests/8/Tests/1-out.json")
                                     (cons "IntegrationTests/8/Tests/2-in.json" "IntegrationTests/8/Tests/2-out.json")
                                     (cons "IntegrationTests/8/Tests/3-in.json" "IntegrationTests/8/Tests/3-out.json")
                                     (cons "IntegrationTests/8/Tests/4-in.json" "IntegrationTests/8/Tests/4-out.json")
                                     (cons "IntegrationTests/8/ForStudents/0-in.json" "IntegrationTests/8/ForStudents/0-out.json")
                                     (cons "IntegrationTests/8/ForStudents/1-in.json" "IntegrationTests/8/ForStudents/1-out.json")
                                     (cons "IntegrationTests/8/ForStudents/2-in.json" "IntegrationTests/8/ForStudents/2-out.json")))
(for ([testcase milestone-7-test-cases])
  (run-test-case "IntegrationTests/8/xbad2" testcase))

(display "--- Fault tolerance 3 ---\n")
;; Test milestone 7
(define milestone-8-test-cases (list (cons "IntegrationTests/9/ForStudents/0-in.json" "IntegrationTests/9/ForStudents/0-out.json")
                                     (cons "IntegrationTests/9/ForStudents/1-in.json" "IntegrationTests/9/ForStudents/1-out.json")
                                     (cons "IntegrationTests/9/ForStudents/2-in.json" "IntegrationTests/9/ForStudents/2-out.json")))
(for ([testcase milestone-8-test-cases])
  (run-test-case "IntegrationTests/10/xbad3" testcase))

(display "--- Fault tolerance 4 ---\n")
;; Test milestone 7
(define milestone-9-test-cases (list (cons "IntegrationTests/10/Tests/0-in.json" "IntegrationTests/10/Tests/0-out.json")
                                     (cons "IntegrationTests/10/Tests/1-in.json" "IntegrationTests/10/Tests/1-out.json")
                                     (cons "IntegrationTests/10/Tests/2-in.json" "IntegrationTests/10/Tests/2-out.json")
                                     (cons "IntegrationTests/10/Tests/3-in.json" "IntegrationTests/10/Tests/3-out.json")
                                     (cons "IntegrationTests/10/Tests/4-in.json" "IntegrationTests/10/Tests/4-out.json")
                                     (cons "IntegrationTests/10/ForStudents/0-in.json" "IntegrationTests/10/ForStudents/0-out.json")
                                     (cons "IntegrationTests/10/ForStudents/1-in.json" "IntegrationTests/10/ForStudents/1-out.json")
                                     (cons "IntegrationTests/10/ForStudents/2-in.json" "IntegrationTests/10/ForStudents/2-out.json")))
(for ([testcase milestone-9-test-cases])
  (run-test-case "IntegrationTests/10/xbad3" testcase))

(display "Done\n")
