#! /usr/bin/env racket
#lang racket/base

(require racket/cmdline)

(define DEFAULT-HOST "127.0.0.1")

(define-values (port host) (command-line #:args (port [host DEFAULT-HOST]) (values (string->number port) host)))