#! /usr/bin/env racket
#lang racket/base

(require json)
(require rackunit)


;; Path (cons Path Path) -> Void
(define (run-test-case executable test-case)
  (define test-case-input-port (open-input-file (car test-case)))
  (define expected-output (read-json (open-input-file (cdr test-case))))
  (define-values (proc child-out child-in e) (subprocess #f test-case-input-port #f #f executable))
  (define actual-output (read-json child-out))
  (check-equal? actual-output expected-output))

;; Test milestone 2
(writeln "Testing milestone 2: xboard")
(define milestone-2-test-cases (list (cons "../3/Tests/0-in.json" "../3/Tests/0-out.json")
                                     (cons "../3/Tests/1-in.json" "../3/Tests/1-out.json")
                                     (cons "../3/Tests/2-in.json" "../3/Tests/2-out.json")))
(for ([testcase milestone-2-test-cases])
  (run-test-case "../3/xboard" testcase))

(writeln "Testing milestone 3: xstate")
;; Test milestone 3
(define milestone-3-test-cases (list (cons "../4/Tests/0-in.json" "../4/Tests/0-out.json")
                                     (cons "../4/Tests/1-in.json" "../4/Tests/1-out.json")
                                     (cons "../4/Tests/2-in.json" "../4/Tests/2-out.json")
                                     (cons "../4/Tests/3-in.json" "../4/Tests/3-out.json")
                                     (cons "../4/Tests/4-in.json" "../4/Tests/4-out.json")))
(for ([testcase milestone-3-test-cases])
  (run-test-case "../4/xstate" testcase))

(writeln "Testing milestone 4: xchoice")
;; Test milestone 4
(define milestone-4-test-cases (list (cons "../5/Tests/0-in.json" "../5/Tests/0-out.json")
                                     (cons "../5/Tests/1-in.json" "../5/Tests/1-out.json")
                                     (cons "../5/Tests/2-in.json" "../5/Tests/2-out.json")
                                     (cons "../5/Tests/3-in.json" "../5/Tests/3-out.json")
                                     (cons "../5/Tests/4-in.json" "../5/Tests/4-out.json")))
(for ([testcase milestone-4-test-cases])
  (run-test-case "../5/xchoice" testcase))

(writeln "Testing milestone 5: xgames")
;; Test milestone 5
(define milestone-5-test-cases (list (cons "../6/Tests/0-in.json" "../6/Tests/0-out.json")
                                     (cons "../6/Tests/1-in.json" "../6/Tests/1-out.json")
                                     (cons "../6/Tests/2-in.json" "../6/Tests/2-out.json")))
(for ([testcase milestone-5-test-cases])
  (run-test-case "../6/xgames" testcase))

(writeln "Testing milestone 6: xgames")
;; Test milestone 6
(define milestone-6-test-cases (list (cons "../7/Tests/0-in.json" "../7/Tests/0-out.json")
                                     (cons "../7/Tests/1-in.json" "../7/Tests/1-out.json")
                                     (cons "../7/Tests/2-in.json" "../7/Tests/2-out.json")))
(for ([testcase milestone-6-test-cases])
  (run-test-case "../7/xbad" testcase))

(writeln "Done")
